apiVersion: 1

datasources:
  - name: MySQL-Agent
    type: mysql
    url: $HOST_DB:$PORT_DB
    database: $NAME_DB
    user: $USERNAME_DB
    password: $PASSWORD_DB
    jsonData:
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+